version: '3'

services:
  serviceregistry:
    image: 'coco2023/serviceregistry:0.0.1'
    container_name: serviceregistry
    ports:
      - '8761:8761'
  configserver:
    image: 'coco2023/configserver:0.0.1'
    container_name: configserver
    ports:
      - '9292:9292'
    environment: 
      - EUREKA_SERVER_ADDRESS=http://serviceregistry:8761/eureka
    depends_on:
      - serviceregistry
  cloudgateway:
    image: 'coco2023/cloudgateway:lastest'
    container_name: cloudgateway
    ports:
      - '9090:9090'
    environment:
      - EUREKA_SERVER_ADDRESS=http://serviceregistry:8761/eureka
      - CONFIG_SERVER_URL=configserver
    depends_on:
      - configserver

